### ISSUE TITLE
Dont use a list here

### ISSUE THREAD

**Issue by Susannova** [Susannova/Discord_Bot#112]
https://github.com/Susannova/Discord_Bot/blob/4c5dd64e05caeee7cfccf847fab642eb6694d708/core/config.py#L100

**Comment by thyanin** [comment]
why not? can this be closed @Susannova

**Comment by Susannova** [comment]
Because usually only the first element of the list is used anyways. It is unneccesary complicated to habe a list here. But some functions accept a list so you can't just replace the list with an int.

**Comment by thyanin** [comment]
so there is no better way to solve this? then we can close this?

**Comment by NickWittig** [comment]
i dont see the issue
