### ISSUE TITLE
Bot messages are always deleted after some time

### ISSUE THREAD

**Issue by Susannova** [Susannova/Discord_Bot#130]
https://github.com/Susannova/Discord_Bot/blob/8fa1670363066b02070122aebf75e5df102f7bee/cogs/cog_play_requests.py#L129

Makes https://github.com/Susannova/Discord_Bot/blob/f3a41ffb201641726cc051fd36a378ebf3409028/cogs/cog_play_requests.py#L91 obsolete.

**Comment by thyanin** [comment]
Are they not supposed to be deleted @Susannova ?

**Comment by Susannova** [comment]
> https://github.com/Susannova/Discord_Bot/blob/f3a41ffb201641726cc051fd36a378ebf3409028/cogs/cog_play_requests.py#L91

This was written to allow play requests like for clash, that are created a day or more before the play time. But the delay time is a constant so it (was) osolete. The code is deleted in 8a1ab8c82ecbd3de79273c1f32b1e3e076745ccc anyways.

**Comment by thyanin** [comment]
so this can be closed then?

**Comment by Susannova** [comment]
Yes but some day we will have this problem again.
