### ISSUE TITLE
New LoL patch message after unclean shutdown

### ISSUE THREAD

**Issue by Susannova** [Susannova/Discord_Bot#141]
If the bot does not perform a clean shutdown, as an example because of power problems, the next time the bot starts, the bot prints a new LoL patch message.

**Comment by thyanin** [comment]
isnt this fixed here?
https://github.com/Susannova/Discord_Bot/blob/9808ba58312e8620019e2403c8c2f72636987b57/riot/riot_utility.py#L76-L89
