### ISSUE TITLE
!play lol doesn't work

### ISSUE THREAD

**Issue by Susannova** [Susannova/Discord_Bot#146]
bug in 4d3c7aec6ec3c4ce1ab2afeed931617b0479579c

File "/home/discord/Discord_Bot/cogs/cog_play_requests.py", line 106, in play
if player_needed_num > 0 and player_needed_num < 20 and type(player_needed_num) == int:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by thyanin** [comment]
fixed in 8bfd00a6cdcaed0a665a8b910a26af23b33402b5
