### ISSUE TITLE
leaderboard command does not work

### ISSUE THREAD

**Issue by thyanin** [Susannova/Discord_Bot#149]
```
File "/home/discord/Discord_Bot/riot/cog_riot.py", line 107, in leaderboard
    summoners.sort(key=lambda x: x.rank_values[queue_type], reverse=True)
  File "/home/discord/Discord_Bot/riot/cog_riot.py", line 107, in <lambda>
    summoners.sort(key=lambda x: x.rank_values[queue_type], reverse=True)
KeyError: 'RANKED_SOLO_5x5'

```
Is the command even needed anymore?

**Comment by Susannova** [comment]
Some people would like to use leaderboard instead of plot, so yes.

**Comment by thyanin** [comment]
This is actually part of a bigger problem. Namely, we do not use the same summoner data in riot and in tasks anymore, which leads to inconsistencies in the data being stored.

**Comment by thyanin** [comment]
> This is actually part of a bigger problem. Namely, we do not use the same summoner data in riot and in tasks anymore, which leads to inconsistencies in the data being stored.

This was not really the case, but I will look over the summoner changes in cog_tasks as that seems really out of place.
