### ISSUE TITLE
config command is useable in #commands channel

### ISSUE THREAD

**Issue by thyanin** [Susannova/Discord_Bot#150]
actually pretty bad if someone just changes the config

**Comment by thyanin** [comment]
@Susannova

**Comment by thyanin** [comment]
fixed in 90812533446c8c01e07cbaa9b2cf1cda3951cefa 
and updated on server locally

**Comment by Susannova** [comment]
oops

**Comment by Susannova** [comment]
Acutally I think it wasn't. It was just useable for you as an admin.
