### ISSUE TITLE
Plot of winrates: Timezone is false

### ISSUE THREAD

**Issue by Susannova** [Susannova/Discord_Bot#69]
https://github.com/Susannova/Discord_Bot/blob/c0ddf1c2e3b7589d71c085d65c85901ec67967cf/cogs/cog_tasks.py#L51

**Comment by thyanin** [comment]
Should be fixed with this https://github.com/Susannova/Discord_Bot/commit/2e28b1b80f0d3457e50386fdc467baede458ffaf#diff-6eee9d7d628b1823a6d6cd6d415b1e7de4889edb69dcf50838955806cd30ae99R14?
